-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgiLgEGojZ54fLxGDP
OYJnrBYPUMjwAntL+DvroeF5cn2gCgYIKoZIzj0DAQehRANCAASGCFD00vmkA7mj
5S2z4ZHO2pAMMOuZywfbAWjA8jXwhlCDSlMzsxpfGlvtyV9f/ZLgbjOVqRIHfyfN
KaNhSgOU
-----END PRIVATE KEY-----