# Generated by Django 5.2.3 on 2025-08-07 10:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('background_color', models.CharField(max_length=255)),
                ('foreground_color', models.CharField(max_length=255)),
                ('label_color', models.CharField(max_length=255)),
                ('logo_url', models.URLField()),
                ('strip_image_url', models.URLField()),
                ('icon_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'configuration',
            },
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=50)),
                ('suggested_section', models.CharField(blank=True, choices=[('header', 'header'), ('primary', 'primary'), ('secondary', 'secondary'), ('back', 'back'), ('auxiliary', 'auxiliary')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'field_definition',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('authentication_token', models.UUIDField()),
                ('web_service_url', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('meta_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loyalty_card',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('business_description', models.TextField()),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vendor',
            },
        ),
        migrations.CreateModel(
            name='PassTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='loyalty.configuration')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loyalty.vendor')),
            ],
            options={
                'db_table': 'pass_template',
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_type', models.CharField(choices=[('header', 'header'), ('primary', 'primary'), ('secondary', 'secondary'), ('back', 'back'), ('auxiliary', 'auxiliary')], max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loyalty.fielddefinition')),
                ('pass_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loyalty.passtemplate')),
            ],
            options={
                'db_table': 'template_field',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loyalty_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='loyalty.loyaltycard')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loyalty.vendor')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
