# Generated by Django 5.2.3 on 2025-08-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='points_system',
            field=models.CharField(blank=True, choices=[('points', 'points'), ('stamps', 'stamps')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='total_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
