# Generated by Django 5.2.3 on 2025-08-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_configuration_points_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
