# Generated by Django 5.2.3 on 2025-08-12 22:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_vendor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='no_of_rewards',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loyaltycard',
            name='reward_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loyaltycard',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(blank=True, choices=[('points', 'points'), ('stamps', 'stamps')], max_length=255, null=True)),
                ('transaction_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('points_remaining', models.IntegerField(blank=True, default=0, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loyalty.customer')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loyalty.vendor')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
