# Generated by Django 5.2.3 on 2025-08-13 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0004_customer_no_of_rewards_customer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='loyalty_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loyalty_card', to='loyalty.loyaltycard'),
        ),
    ]
