# Generated by Django 5.2.3 on 2025-08-13 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0006_alter_customer_loyalty_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='loyalty_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='loyalty.loyaltycard'),
        ),
    ]
