# Generated by Django 5.2.3 on 2025-08-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0007_alter_customer_loyalty_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted')], default='active', max_length=255),
        ),
    ]
