# Generated by Django 5.2.3 on 2025-08-13 21:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0008_customer_date_of_birth_alter_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted')], default='active', max_length=255),
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('available', 'available'), ('availed', 'availed'), ('expired', 'expired')], default='active', max_length=255)),
                ('availed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loyalty.customer')),
            ],
            options={
                'db_table': 'reward',
            },
        ),
    ]
